//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shveynaya_Fabrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furnitura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furnitura()
        {
            this.Tip = new HashSet<Tip>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public double Shirina { get; set; }
        public Nullable<double> Dlina { get; set; }
        public decimal Cena { get; set; }
        public Nullable<double> Ves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tip> Tip { get; set; }
    }
}
