//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shveynaya_Fabrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdeliya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdeliya()
        {
            this.TkaniIzdeliya = new HashSet<TkaniIzdeliya>();
        }
    
        public string Articul { get; set; }
        public string Naimenovanie { get; set; }
        public double Shirina { get; set; }
        public double Dlina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TkaniIzdeliya> TkaniIzdeliya { get; set; }
    }
}
