//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shveynaya_Fabrika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SFabricaEntities1 : DbContext
    {
        public SFabricaEntities1()
            : base("name=SFabricaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUser { get; set; }
        public virtual DbSet<Cvet> Cvet { get; set; }
        public virtual DbSet<Furnitura> Furnitura { get; set; }
        public virtual DbSet<Izdeliya> Izdeliya { get; set; }
        public virtual DbSet<Risunok> Risunok { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sostav> Sostav { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<Tkani> Tkani { get; set; }
        public virtual DbSet<TkaniIzdeliya> TkaniIzdeliya { get; set; }
    }
}
